import type { SkillSection } from '@/types';

export const SECTION_MODELING: SkillSection = {
  id: 'data-modeling',
  title: 'データモデリング',
  description: 'スタースキーマとfact/dimテーブルの設計思想を習得する',
  icon: '⭐',
  accent: '#F87171',
  bg: '#140400',
  upsell: {
    questId: 'ec-site',
    message: '実際にスタースキーマを設計するWarehouseステージを体験しよう',
    label: 'ECサイト Warehouse ステージを試す →',
  },
  lessons: [
    {
      id: 'star-schema',
      title: 'スタースキーマとは？',
      description: '分析に最適化されたデータモデルの基本を学ぶ',
      icon: '⭐',
      xpReward: 40,
      concept: {
        title: '分析クエリを高速化するモデル',
        body: 'スタースキーマは分析用に最適化されたデータモデルです。\n\n中心に fact（事実）テーブル、周辺に dim（ディメンション）テーブルを配置します。JOINが単純になり、BIツールからのクエリが高速化します。Warehouse Layer の標準的なモデリング手法です。',
      },
      questions: [
        {
          id: 'q1',
          type: 'fill_blank',
          question: 'スタースキーマで中心に置く「計測値テーブル」のプレフィックスを書いてください。例: ??? + orders = fact_orders',
          answer: 'fact_',
          acceptedAnswers: ['fact'],
          placeholder: '????_',
          explanation: 'fact_ プレフィックスが正解です。factテーブルは「出来事」を記録し、数値（金額・数量）と外部キーを持ちます。周囲の属性テーブルは dim_（dimension）プレフィックスを使います。',
        },
        {
          id: 'q2',
          type: 'true_false',
          question: 'スタースキーマの "スター" という名前は、図に描くとfactテーブルを中心にdimテーブルが星形に広がることに由来する。',
          correct: true,
          explanation: '✓ fact_ordersを中心に、dim_users・dim_products・dim_dateが放射状につながる形が星（スター）に見えることからこの名前がつきました。',
        },
        {
          id: 'q3',
          type: 'multiple_choice',
          question: 'スタースキーマが分析クエリに適している理由はどれですか？',
          options: [
            { label: 'テーブルを正規化しているので容量が小さい', correct: false },
            { label: 'JOINの数が少なく、クエリが単純で高速', correct: true },
            { label: 'エラーが発生しないから', correct: false },
            { label: 'NULLが含まれないから', correct: false },
          ],
          explanation: 'スタースキーマはfact + 少数のdimのJOINで多くの分析クエリを書けます。正規化（3NF）は更新・削除には強いですが、分析には不向きです。BIツールの多くはスタースキーマを前提に設計されています。',
        },
        {
          id: 'q4',
          type: 'ordering',
          question: 'ECサイトのスタースキーマ設計の手順を正しい順に並べてください。',
          items: [
            'fact_orders に user_key・product_key 外部キーを設定',
            '分析したいビジネス上の「出来事」（注文）を特定',
            'dim_users・dim_products にサロゲートキーを追加',
            '注文の属性（ユーザー・商品）をdimテーブルに分離',
          ],
          correctOrder: [1, 3, 2, 0],
          explanation: 'まず「何の出来事を分析するか」を決め→属性を分離してdimを設計→サロゲートキー付与→factにキーを設定、の順です。',
        },
      ],
    },
    {
      id: 'fact-dim',
      title: 'factとdimを分ける判断基準',
      description: 'どのデータをfactに置き、dimに置くかを判断できるようになる',
      icon: '🗂️',
      xpReward: 50,
      concept: {
        title: '何を計測し、何で切り分けるか',
        body: 'fact テーブルは「売上・注文数・クリック数」など計測対象の数値データを持ちます。\n\ndim テーブルは「ユーザー・商品・日付」など分析の切り口となる属性情報です。\n\nfact と dim を正しく設計することで、任意の切り口での集計・フィルタリングが可能になります。',
      },
      questions: [
        {
          id: 'q1',
          type: 'multiple_choice',
          question: '次のカラムのうち、factテーブルに置くべきものはどれですか？',
          options: [
            { label: 'user_name（ユーザー名）', correct: false },
            { label: 'product_category（商品カテゴリ）', correct: false },
            { label: 'amount（注文金額）', correct: true },
            { label: 'email（メールアドレス）', correct: false },
          ],
          explanation: 'factテーブルには「集計できる数値」と「外部キー」だけを置きます。amount は SUM・AVG などで集計できる典型的なfactカラムです。name・category・email は属性（dim）です。',
        },
        {
          id: 'q2',
          type: 'true_false',
          question: 'dimテーブルの行数は、factテーブルの行数より通常はるかに少ない。',
          correct: true,
          explanation: '✓ dim_users はユーザー数分（数百〜数万行）しかありません。一方 fact_orders は全注文分（数百万行以上）になります。factは高頻度で増え続けますが、dimの変化はゆっくりです。',
        },
        {
          id: 'q3',
          type: 'multiple_choice',
          question: 'サロゲートキー（surrogate key）とは何ですか？',
          options: [
            { label: 'ユーザーIDなどビジネスが使っている自然キー', correct: false },
            { label: 'パイプラインが付与する連番の代理キー', correct: true },
            { label: 'NULL値を置き換えるための仮のキー', correct: false },
            { label: 'プライマリキーの別名', correct: false },
          ],
          explanation: 'サロゲートキー（例：ROW_NUMBER()で生成）はビジネスキー（U-1, U-2等）とは独立した、DWH側が管理する連番です。ソースシステムの変更に影響されずfact-dim間のJOINを安定させます。',
        },
        {
          id: 'q4',
          type: 'multiple_choice',
          question: 'fact_orders に user_key ではなく user_id（元のビジネスキー）をそのまま使うデメリットはなぜですか？',
          options: [
            { label: 'user_id は長すぎてストレージを圧迫する', correct: false },
            { label: 'ソースシステムでユーザーIDの体系が変わると結合できなくなる', correct: true },
            { label: 'user_id を使うと重複が発生する', correct: false },
            { label: '特にデメリットはない', correct: false },
          ],
          explanation: 'ビジネスキーはソースシステムの都合で変わることがあります（U-1→USER-0001等）。サロゲートキーはDWH内部で管理するため、ソースの変更に影響を受けません。これがサロゲートキーを使う主な理由です。',
        },
        {
          id: 'q5',
          type: 'true_false',
          question: 'スタースキーマでは、fact_orders に商品名（product_name）を直接持たせるべきである。',
          correct: false,
          explanation: '✗ 商品名はdim_productsに持たせます。fact_ordersにはproduct_keyのみを置き、商品名が必要な場合はdim_productsをJOINします。商品名が変わっても、factのデータを変更する必要がなくなります。',
        },
      ],
    },
    {
      id: 'grain',
      title: '粒度（Grain）を定義する',
      description: 'テーブルの1行が何を表すかを明確に定義することの重要性',
      icon: '🔬',
      xpReward: 50,
      concept: {
        title: '粒度はfactテーブル設計の核心',
        body: '粒度（Grain）とは、fact テーブルの1行が「何」を表すかです。\n\n「1注文に1行」なのか「1注文明細に1行」なのかで、集計結果が全く変わります。設計の最初に粒度を明示的に定義することが、モデリングミスを防ぐ最重要ステップです。',
      },
      questions: [
        {
          id: 'q1',
          type: 'multiple_choice',
          question: 'データモデリングで「粒度（Grain）」とは何ですか？',
          options: [
            { label: 'テーブルの行数', correct: false },
            { label: 'テーブルの1行が何を表すか（1行の定義）', correct: true },
            { label: 'カラムの数', correct: false },
            { label: 'データの更新頻度', correct: false },
          ],
          explanation: '粒度は「このテーブルの1行は何？」を明確にすることです。fact_ordersの粒度は「1注文につき1行」です。粒度が曖昧なテーブルは集計時に重複や欠損が起きます。',
        },
        {
          id: 'q2',
          type: 'true_false',
          question: 'fact_orders の粒度が「1注文1行」の場合、同じ注文が2行あるのは粒度違反である。',
          correct: true,
          explanation: '✓ 粒度が「1注文1行」なのに重複があるのは設計違反です。重複を排除するか、粒度を「1注文明細1行」に変更する必要があります。粒度の違反はダブルカウントの原因になります。',
        },
        {
          id: 'q3',
          type: 'multiple_choice',
          question: 'mart_sales_by_dow（曜日別売上）の粒度として正しいのはどれですか？',
          options: [
            { label: '1注文につき1行', correct: false },
            { label: '1ユーザーにつき1行', correct: false },
            { label: '1曜日につき1行', correct: true },
            { label: '1商品につき1行', correct: false },
          ],
          explanation: 'mart_sales_by_dow は曜日ごとに集計したテーブルなので「1曜日1行」が粒度です。GROUP BY day_of_week で7行（月〜日）になります。',
        },
        {
          id: 'q4',
          type: 'ordering',
          question: 'データモデリングの設計手順を正しい順に並べてください。',
          items: [
            'factテーブルのカラム（数値・外部キー）を定義',
            'ビジネスの問いに答えるための「出来事」を特定',
            '粒度を明確に決める（1行 = 何？）',
            'dimテーブルに属性情報を配置',
          ],
          correctOrder: [1, 2, 3, 0],
          explanation: '出来事の特定→粒度の定義→dim設計→factのカラム定義の順がデータモデリングの基本フローです。',
        },
      ],
    },
    {
      id: 'modeling-practice',
      title: 'モデリング実践クイズ',
      description: 'スタースキーマ設計の判断力を鍛える総まとめ',
      icon: '🏆',
      xpReward: 60,
      concept: {
        title: '設計の判断を実戦で磨く',
        body: 'スタースキーマの知識を実際のデータに適用します。\n\n「このカラムは fact か dim か？」「粒度はどこに設定すべきか？」という判断を繰り返すことで、モデリングの感覚が身につきます。正解は1つではなく、ビジネス要件によって変わります。',
      },
      questions: [
        {
          id: 'q1',
          type: 'multiple_choice',
          question: '"ユーザーが商品をレビューした" というイベントをモデル化する場合、factテーブルに入れるべきカラムはどれですか？',
          options: [
            { label: 'user_name, product_name, review_text', correct: false },
            { label: 'user_key, product_key, rating（評価点数）, reviewed_at', correct: true },
            { label: 'email, category, review_date_formatted', correct: false },
            { label: 'review_id だけ', correct: false },
          ],
          explanation: 'factには外部キー（user_key, product_key）と数値（rating）と日時（reviewed_at）を置きます。名前やメールはdimに任せます。',
        },
        {
          id: 'q2',
          type: 'true_false',
          question: 'dim_date（日付ディメンション）を作ることで、曜日・週・月・四半期などの集計が簡単になる。',
          correct: true,
          explanation: '✓ dim_date は「カレンダーテーブル」とも呼ばれ、日付から曜日名・週番号・月・四半期・祝日フラグ等を取得できます。Mart Layerでの日付集計が格段に楽になります。',
        },
        {
          id: 'q3',
          type: 'fill_blank',
          question: 'dimテーブルの属性が時間とともに変化する問題への対処設計パターンを、略称3文字で答えてください。',
          answer: 'SCD',
          acceptedAnswers: ['scd', 'Slowly Changing Dimension', 'slowly changing dimension'],
          placeholder: '???',
          explanation: 'SCD（Slowly Changing Dimension）が正解です。ユーザーの住所変更・商品カテゴリの変更など、dimの属性は変わることがあります。履歴をどう保持するかの設計パターンです。',
        },
        {
          id: 'q4',
          type: 'ordering',
          question: 'ECサイトのスタースキーマを完成させる作業を正しい順に並べてください。',
          items: [
            'fact_orders を stg_orders・dim_users・dim_products の JOIN で作成',
            'stg_orders のデータ品質を確認',
            'dim_users に user_key（ROW_NUMBER）を追加して作成',
            'dim_products に product_key を追加して作成',
          ],
          correctOrder: [1, 2, 3, 0],
          explanation: 'まずStagingのデータ品質確認→dimテーブル作成（サロゲートキー付き）→factテーブル作成（JOIN）の順です。factはdimが存在しないとJOINできないため、dim先行が原則です。',
        },
        {
          id: 'q5',
          type: 'multiple_choice',
          question: 'なぜWarehouse Layerの設計を「スタースキーマ」にするのか、最も根本的な理由はどれですか？',
          options: [
            { label: 'スタースキーマが業界の規格だから', correct: false },
            { label: '分析クエリがシンプルになり、BIツールとの相性もよいから', correct: true },
            { label: 'factとdimを分けることでデータが減るから', correct: false },
            { label: 'NULLが発生しなくなるから', correct: false },
          ],
          explanation: 'スタースキーマは「分析のしやすさ」のために設計されています。BIツール（Looker・Tableau等）はスタースキーマを前提に動作するものが多く、シンプルなJOINで豊富な分析ができます。',
        },
      ],
    },
  ],
};
