import type { SkillSection } from '@/types';

export const SECTION_QUALITY: SkillSection = {
  id: 'data-quality',
  title: 'データ品質',
  description: '汚いデータは誤った意思決定を生む。品質問題を発見・修正する力を鍛える',
  icon: '🔍',
  accent: '#34D399',
  bg: '#020f0a',
  upsell: {
    questId: 'ec-site',
    message: '実際の汚れたデータをStagingステージで修正しよう',
    label: 'ECサイト Staging ステージを試す →',
  },
  lessons: [
    {
      id: 'what-is-quality',
      title: 'データ品質とは？',
      description: 'データ品質の6つの次元と、なぜ重要かを理解する',
      icon: '⚠️',
      xpReward: 30,
      questions: [
        {
          id: 'q1',
          type: 'multiple_choice',
          question: '次のうち「データ品質問題」に該当するのはどれですか？',
          options: [
            { label: 'テーブルの行数が多い', correct: false },
            { label: 'status カラムに "Completed" "completed" "COMPLETED" が混在している', correct: true },
            { label: 'データが毎日更新される', correct: false },
            { label: 'テーブルに100個のカラムがある', correct: false },
          ],
          explanation: '表記揺れはデータ品質問題の代表例です。"Completed" と "completed" は人間には同じに見えますが、コンピュータは別の値として扱います。集計すると数値がずれる原因になります。',
        },
        {
          id: 'q2',
          type: 'true_false',
          question: 'データ品質が低いと、正しい集計ができず誤った経営判断につながる可能性がある。',
          correct: true,
          explanation: '✓ これがデータ品質が重要な理由です。"COMPLETED" の売上が集計から漏れると、実際の売上より低い数字が出て、誤った施策を打つことになります。',
        },
        {
          id: 'q3',
          type: 'multiple_choice',
          question: 'データ品質の修正は、どのレイヤーで行うべきですか？',
          options: [
            { label: 'Source Layer（原本を直接修正）', correct: false },
            { label: 'Staging Layer（クレンジング専門）', correct: true },
            { label: 'Mart Layer（集計時に修正）', correct: false },
            { label: '全てのレイヤーで分散して修正', correct: false },
          ],
          explanation: 'データ品質の修正は必ずStaging Layerで行います。Source Layerの原本は絶対に変更しません。Mart Layerで修正すると問題が下流にしか効かず、他の分析に品質問題が残ります。',
        },
        {
          id: 'q4',
          type: 'ordering',
          question: 'データ品質問題を発見・修正するプロセスを正しい順に並べてください。',
          items: [
            'src_orders で品質問題を確認（SELECT文で調査）',
            'stg_orders に修正済みデータを格納',
            '品質ルールを定義（NULL許可/不許可・型・表記統一）',
            '修正クエリを書いてテスト',
          ],
          correctOrder: [2, 0, 3, 1],
          explanation: 'まずルールを決め→問題を発見し→修正クエリを書き→Stagingに格納するのが正しいフローです。',
        },
      ],
    },
    {
      id: 'null-handling',
      title: 'NULLを扱う',
      description: 'NULL の正しい理解と、ビジネスへの影響を学ぶ',
      icon: '🕳️',
      xpReward: 40,
      questions: [
        {
          id: 'q1',
          type: 'fill_blank',
          question: 'SQL で NULL + 100 を計算すると結果はどうなりますか？（英大文字4文字で）',
          answer: 'NULL',
          placeholder: '????',
          explanation: 'NULL は「不明な値」です。不明な値に何を足しても結果は不明（NULL）になります。これが NULL を含む amount を SUM すると正しい合計が出ない理由です。',
        },
        {
          id: 'q2',
          type: 'fill_blank',
          question: 'amount が NULL かどうかを判定するSQL演算子を書いてください。（WHERE amount ??? ）',
          answer: 'IS NULL',
          acceptedAnswers: ['is null'],
          placeholder: 'IS ???',
          explanation: 'NULL との比較には「= NULL」は使えません。正しくは「IS NULL」です。NULL は値ではなく「不明」なので、等号比較（=）が成立しません。',
        },
        {
          id: 'q3',
          type: 'multiple_choice',
          question: 'amount カラムに NULL が含まれる場合、SUM(amount) の結果はどうなりますか？',
          options: [
            { label: '計算がエラーになる', correct: false },
            { label: 'NULL を 0 として計算する', correct: false },
            { label: 'NULL を無視して他の値の合計を返す', correct: true },
            { label: 'NULL があると SUM は NULL を返す', correct: false },
          ],
          explanation: 'SUM は NULL を無視します。ただし「NULL = 0」ではないため、NULL の注文は集計から除外されます。「NULL = 金額不明の注文が集計されていない」という解釈が正しいです。',
        },
        {
          id: 'q4',
          type: 'multiple_choice',
          question: 'VARCHAR 型の "NULL" 文字列と、本当の NULL 値の違いとして正しいのはどれですか？',
          options: [
            { label: '違いはない、どちらも同じ', correct: false },
            { label: '"NULL" 文字列は IS NULL で検出できる', correct: false },
            { label: '"NULL" は6文字の文字列で、IS NULL では検出できない', correct: true },
            { label: '本当の NULL は SUM で 0 として扱われる', correct: false },
          ],
          explanation: '"NULL" は文字列（6文字）であり、IS NULL では検出できません。CSVから読み込むと "NULL" 文字列として入ることがあり、TRY_CAST で変換すると本当の NULL になります。これがSource Layerで発生しやすい問題です。',
        },
        {
          id: 'q5',
          type: 'true_false',
          question: 'TRY_CAST(amount AS NUMERIC) を使うと、変換できない値（"NULL"文字列など）を NULL として安全に処理できる。',
          correct: true,
          explanation: '✓ TRY_CAST は変換に失敗した場合にエラーを出さず NULL を返します。CAST を使うとエラーで処理が止まりますが、TRY_CAST はデータ品質問題を安全に処理できます。',
        },
      ],
    },
    {
      id: 'type-casting',
      title: '型変換のベストプラクティス',
      description: 'CSVデータの型問題を正しく処理する',
      icon: '🔧',
      xpReward: 40,
      questions: [
        {
          id: 'q1',
          type: 'multiple_choice',
          question: 'CSVから読み込んだデータのカラムが全てVARCHARになる理由はなぜですか？',
          options: [
            { label: 'バグです', correct: false },
            { label: 'CSVはテキストファイルなので、型情報を持たないから', correct: true },
            { label: 'DuckDBの制限', correct: false },
            { label: 'VARCHAR型が最も速いから', correct: false },
          ],
          explanation: 'CSVはカンマ区切りのテキストです。型情報が含まれていないため、読み込み時は全て文字列になります。数値・日付などへの変換はStaging Layerの仕事です。',
        },
        {
          id: 'q2',
          type: 'fill_blank',
          question: 'NULL を別の値で置き換えるSQL関数は何ですか？ 例: ???(amount, 0) → NULLなら0を返す',
          answer: 'COALESCE',
          acceptedAnswers: ['coalesce'],
          placeholder: '関数名を入力...',
          explanation: 'COALESCE(値, デフォルト) は第1引数がNULLのとき第2引数を返します。Staging Layerでの定番パターン: COALESCE(amount, 0) でNULLを0に、COALESCE(status, \'unknown\') で不明ステータスを設定します。',
        },
        {
          id: 'q3',
          type: 'ordering',
          question: 'Staging Layer でのデータクレンジング処理を、適切な実行順に並べてください。',
          items: [
            'stg_orders テーブルを CREATE OR REPLACE で作成',
            'src_orders の品質問題をSELECT文で調査',
            'クレンジング結果をSELECT文で検証',
            'TRY_CAST・LOWER・TRIM 等のクレンジング処理を書く',
          ],
          correctOrder: [1, 3, 0, 2],
          explanation: '調査→処理設計→テーブル作成→検証の順です。検証を最後に行うことで「本当にクレンジングできているか」を確認できます。',
        },
        {
          id: 'q4',
          type: 'multiple_choice',
          question: 'registered_at カラムが "2024/01/05" と "2024-01-01" で混在しています。Staging Layer での正しい対処はどれですか？',
          options: [
            { label: 'src_users のデータを直接修正する', correct: false },
            { label: 'CAST(registered_at AS DATE) でDATE型に統一してstg_usersに格納する', correct: true },
            { label: 'どちらの形式でも集計できるので修正しない', correct: false },
            { label: 'mart_users で修正する', correct: false },
          ],
          explanation: 'DuckDBのCAST・TRY_CAST は複数の日付フォーマットを解釈できます。Staging Layerで統一することで、Warehouse・Mart では正規化済みの日付を安全に使えます。',
        },
      ],
    },
    {
      id: 'quality-checks',
      title: 'データ品質チェック実践',
      description: '品質問題を発見するSQLパターンを身につける',
      icon: '✅',
      xpReward: 50,
      questions: [
        {
          id: 'q1',
          type: 'multiple_choice',
          question: 'status カラムに予期しない値がないか確認するSQLとして正しいのはどれですか？',
          options: [
            { label: 'SELECT status FROM orders WHERE status = NULL', correct: false },
            { label: "SELECT DISTINCT status FROM stg_orders WHERE status NOT IN ('completed','cancelled','pending')", correct: true },
            { label: 'SELECT COUNT(*) FROM orders', correct: false },
            { label: 'SELECT status, COUNT(*) FROM orders GROUP BY status HAVING COUNT(*) > 1', correct: false },
          ],
          explanation: 'DISTINCT + NOT IN のパターンは「想定外の値を発見する」ための典型的な品質チェックSQLです。dbtでもこのパターンでバリデーションを書きます。',
        },
        {
          id: 'q2',
          type: 'true_false',
          question: 'データ品質チェックは、パイプラインの各レイヤー間（Staging完了後・Warehouse完了後）で行うのがベストプラクティスである。',
          correct: true,
          explanation: '✓ 問題が下流に伝播する前に各レイヤーで検証するのがベストプラクティスです。dbtのtestsはまさにこのアイデアを実装したものです。',
        },
        {
          id: 'q3',
          type: 'multiple_choice',
          question: '重複データ（同じorder_idが2行ある）を発見するSQLとして正しいのはどれですか？',
          options: [
            { label: 'SELECT * FROM orders WHERE order_id IS NOT NULL', correct: false },
            { label: 'SELECT order_id, COUNT(*) FROM orders GROUP BY order_id HAVING COUNT(*) > 1', correct: true },
            { label: 'SELECT DISTINCT order_id FROM orders', correct: false },
            { label: 'SELECT * FROM orders WHERE order_id = order_id', correct: false },
          ],
          explanation: 'GROUP BY + HAVING COUNT(*) > 1 は重複を発見する基本パターンです。「同じ値で2件以上ある行を返す」という意味です。',
        },
        {
          id: 'q4',
          type: 'multiple_choice',
          question: 'データ品質の問題として「鮮度（Freshness）」とは何ですか？',
          options: [
            { label: 'データが正しく型変換されているか', correct: false },
            { label: 'データが期待する頻度で更新されているか', correct: true },
            { label: 'NULL値が少ないか', correct: false },
            { label: 'テーブルの行数が多いか', correct: false },
          ],
          explanation: 'データ品質の6次元（正確性・完全性・一貫性・適時性・一意性・妥当性）の中で「鮮度（適時性）」は「期待するタイミングでデータが更新されているか」を指します。昨日のデータがないのに気づかず古いデータで分析するのは重大な問題です。',
        },
      ],
    },
  ],
};
