import type { SkillSection } from '@/types';

export const SECTION_PIPELINE: SkillSection = {
  id: 'pipeline-basics',
  title: 'パイプライン基礎',
  description: 'データが原石から意思決定の武器になるまでの旅を理解する',
  icon: '🗺️',
  accent: '#818CF8',
  bg: '#0c0c28',
  upsell: {
    questId: 'ec-site',
    message: 'パイプライン設計を実際のECサイトデータで試してみよう',
    label: 'ECサイトクエストで実践する →',
  },
  lessons: [
    {
      id: 'what-is-pipeline',
      title: 'データパイプラインとは？',
      description: '生データが意思決定データになるまでの仕組みを理解する',
      icon: '🔄',
      xpReward: 30,
      concept: {
        title: 'データを原石から宝石に変える旅',
        body: '散らばった生データを収集・整形・分析できる状態に変換する仕組みがデータパイプラインです。\n\nSource → Staging → Warehouse → Mart の4層で構成され、上流から下流に向かってデータが変換されていきます。パイプラインがなければ、複数システムのデータを統合した分析は不可能です。',
      },
      questions: [
        {
          id: 'q1',
          type: 'multiple_choice',
          question: 'データパイプラインの主な目的は何ですか？',
          options: [
            { label: '生データをそのまま保存するだけ', correct: false },
            { label: '生データを意思決定に使える形に変換する', correct: true },
            { label: 'データを削除して容量を節約する', correct: false },
            { label: 'データベースのバックアップを取る', correct: false },
          ],
          explanation: 'データパイプラインは、散らばった生データを収集・整形・モデリングして、ビジネスが意思決定に使える状態にする仕組みです。',
        },
        {
          id: 'q2',
          type: 'true_false',
          question: 'Source Layer では、取り込んだデータを加工・クレンジングしてから保存する。',
          correct: false,
          explanation: '✗ Source Layer は生データをそのまま保存するのが鉄則です。加工するのは Staging Layer の役割。原本を保持することで、処理が失敗しても最初からやり直せます。',
        },
        {
          id: 'q3',
          type: 'ordering',
          question: 'データパイプラインの4層を、上流から下流の順に並べてください。',
          items: ['Warehouse Layer', 'Source Layer', 'Mart Layer', 'Staging Layer'],
          correctOrder: [1, 3, 0, 2],
          explanation: '正しい順番は Source → Staging → Warehouse → Mart です。上流（生データ）から下流（意思決定データ）に向かって変換が進みます。',
        },
        {
          id: 'q4',
          type: 'fill_blank',
          question: 'Source Layer で生データに追加してよい唯一の監査カラムは何ですか？（アンダースコアで始まる）',
          answer: '_loaded_at',
          acceptedAnswers: ['loaded_at'],
          placeholder: '_????_??',
          explanation: '唯一の例外は _loaded_at（いつ取り込んだかの記録）です。選択肢を見なくてもこの名前を書けるようになると、Source Layerの設計が体に染み込んでいる証拠です。',
        },
        {
          id: 'q5',
          type: 'true_false',
          question: 'データパイプラインがあれば、複数のシステムに散らばったデータを一箇所で分析できるようになる。',
          correct: true,
          explanation: '✓ これがデータパイプラインの本質的な価値です。Shopify・CRM・在庫システムなど複数のソースを統合し、一元的な分析基盤を作ります。',
        },
      ],
    },
    {
      id: '4-layers',
      title: '4層構造を理解する',
      description: '各レイヤーの役割と特徴を学ぶ',
      icon: '🏗️',
      xpReward: 40,
      concept: {
        title: '各レイヤーの役割と責務',
        body: '4層それぞれに明確な責務があります。\n\n・Source：生データをそのまま保存（加工禁止）\n・Staging：クレンジング・型変換・表記統一\n・Warehouse：スタースキーマでモデリング\n・Mart：ビジネス用途に特化した集計テーブル\n\n層を混在させないことが設計の基本原則です。',
      },
      questions: [
        {
          id: 'q1',
          type: 'multiple_choice',
          question: 'Staging Layer の主な役割はどれですか？',
          options: [
            { label: '生データをそのまま保存する', correct: false },
            { label: 'KPI集計テーブルを作る', correct: false },
            { label: 'データのクレンジング・型変換・表記揺れ修正', correct: true },
            { label: 'スタースキーマの設計', correct: false },
          ],
          explanation: 'Staging Layer は「クレンジング専門」のレイヤーです。型変換・NULL処理・表記揺れ修正など、データ品質の問題をここで全て解決します。',
        },
        {
          id: 'q2',
          type: 'multiple_choice',
          question: 'Warehouse Layer で主に使われるデータモデリング手法はどれですか？',
          options: [
            { label: '正規化（3NF）', correct: false },
            { label: 'スタースキーマ', correct: true },
            { label: 'ドキュメント指向', correct: false },
            { label: 'グラフモデル', correct: false },
          ],
          explanation: 'スタースキーマは分析クエリを高速化するために設計されたモデルです。中心の fact テーブルと周辺の dim テーブルで構成されます。',
        },
        {
          id: 'q3',
          type: 'true_false',
          question: 'Mart Layer のテーブルは、マーケティングや経営などビジネス部門が直接使うことを想定して設計する。',
          correct: true,
          explanation: '✓ Mart Layer はビジネス用途に特化したテーブルを持ちます。曜日別売上・ユーザーコホートなど、特定の分析目的に最適化されたテーブルです。',
        },
        {
          id: 'q4',
          type: 'ordering',
          question: '次の作業を、データパイプラインで実行される正しい順に並べてください。',
          items: [
            'fact_orders と dim_users を JOIN してスタースキーマ構築',
            'orders.csv をそのまま src_orders テーブルに格納',
            '曜日別売上 KPI テーブルを作成',
            'amount の型を VARCHAR → NUMERIC に変換',
          ],
          correctOrder: [1, 3, 0, 2],
          explanation: 'Source（格納）→ Staging（整形）→ Warehouse（モデリング）→ Mart（集計）の順で処理が進みます。',
        },
        {
          id: 'q5',
          type: 'fill_blank',
          question: 'Staging Layer のテーブル名に使うプレフィックス（接頭辞）を書いてください。例: ??? + orders = stg_orders',
          answer: 'stg_',
          acceptedAnswers: ['stg'],
          placeholder: '???_',
          explanation: 'src_（Source）・stg_（Staging）・fact_/dim_（Warehouse）・mart_（Mart）の4つを覚えることで、テーブル名を見ただけでレイヤーが分かります。',
        },
      ],
    },
    {
      id: 'elt-vs-etl',
      title: 'ELT vs ETL',
      description: '現代のデータエンジニアリングはなぜ ELT を選ぶのか',
      icon: '⚡',
      xpReward: 40,
      concept: {
        title: 'ETL から ELT へのシフト',
        body: 'ETL（Extract→Transform→Load）は変換してからDWHに格納する旧来の方式です。\n\nELT（Extract→Load→Transform）はまずDWHに格納し、DWH内で変換します。BigQuery・Snowflakeなどクラウド DWH の処理能力が飛躍的に向上した結果、現代は ELT が主流になりました。',
      },
      questions: [
        {
          id: 'q1',
          type: 'multiple_choice',
          question: 'ETL の正しい処理順序はどれですか？',
          options: [
            { label: 'Extract → Load → Transform', correct: false },
            { label: 'Extract → Transform → Load', correct: true },
            { label: 'Transform → Extract → Load', correct: false },
            { label: 'Load → Extract → Transform', correct: false },
          ],
          explanation: 'ETL は Extract（抽出）→ Transform（変換）→ Load（格納）の順です。変換をしてからDWHに入れる旧来の方式です。',
        },
        {
          id: 'q2',
          type: 'true_false',
          question: 'ELT では、データをまずそのままDWHに格納してから、DWH内で変換を行う。',
          correct: true,
          explanation: '✓ ELT は Extract → Load → Transform の順です。クラウドDWH（BigQuery・Snowflake・DuckDB等）の強力な処理能力を活用して、格納後に変換します。',
        },
        {
          id: 'q3',
          type: 'multiple_choice',
          question: '現代でELTがETLより主流になった最大の理由はどれですか？',
          options: [
            { label: 'ELTのほうがコードが短く書けるから', correct: false },
            { label: 'クラウドDWHの処理能力が向上し、DWH内変換が高速になったから', correct: true },
            { label: 'ETLが法律で禁止されたから', correct: false },
            { label: 'ELTはエラーが発生しないから', correct: false },
          ],
          explanation: 'BigQuery・Snowflake・RedshiftなどのクラウドDWHは大量データを高速処理できます。そのため「変換前に格納」してDWH内で変換するELTが効率的になりました。',
        },
        {
          id: 'q4',
          type: 'true_false',
          question: 'dbt（data build tool）は、ELTの「T（Transform）」を担う代表的なツールである。',
          correct: true,
          explanation: '✓ dbt はDWH内のデータをSQLで変換するツールです。Staging・Warehouse・Mart各レイヤーの変換処理を管理します。このアプリで体験する処理はdbtが担う役割そのものです。',
        },
        {
          id: 'q5',
          type: 'multiple_choice',
          question: 'ELTで生データをそのままDWHに格納する利点はどれですか？',
          options: [
            { label: 'ストレージコストが下がる', correct: false },
            { label: '変換処理が失敗しても原本から再実行できる', correct: true },
            { label: 'データの容量が自動的に圧縮される', correct: false },
            { label: 'SQLを書かなくてよくなる', correct: false },
          ],
          explanation: '原本（生データ）を保持するELTは、変換ロジックを修正してやり直せます。ETLは変換後しか残らないため、バグがあると遡れません。これがSource Layerを加工しない理由です。',
        },
      ],
    },
    {
      id: 'naming-conventions',
      title: '命名規則とデータガバナンス',
      description: 'チームで壊れないパイプラインを作るための命名ルール',
      icon: '📋',
      xpReward: 30,
      concept: {
        title: 'テーブル名でレイヤーを即座に識別する',
        body: '命名規則を徹底すると、テーブル名を見ただけでレイヤーが分かります。\n\n・src_ → Source Layer\n・stg_ → Staging Layer\n・fact_ / dim_ → Warehouse Layer\n・mart_ → Mart Layer\n\nチーム全員が同じ規則を使うことで、コードレビューとデバッグが劇的に速くなります。',
      },
      questions: [
        {
          id: 'q1',
          type: 'fill_blank',
          question: 'Source Layer のテーブル名に使うプレフィックスを書いてください。例: ??? + orders = src_orders',
          answer: 'src_',
          acceptedAnswers: ['src'],
          placeholder: '???_',
          explanation: 'src_（Source）が正解です。4つのプレフィックス src_ / stg_ / fact_ dim_ / mart_ を覚えることで、SQLを見ただけでデータの流れを追えるようになります。',
        },
        {
          id: 'q2',
          type: 'ordering',
          question: '以下のテーブルを、パイプラインの上流から下流の順に並べてください。',
          items: ['mart_sales_by_dow', 'src_orders', 'stg_orders', 'fact_orders'],
          correctOrder: [1, 2, 3, 0],
          explanation: 'src_（Source）→ stg_（Staging）→ fact_（Warehouse）→ mart_（Mart）がプレフィックスから読み取れる正しい順序です。',
        },
        {
          id: 'q3',
          type: 'true_false',
          question: 'データカタログ（テーブルの説明書）を整備することもデータエンジニアの仕事のひとつである。',
          correct: true,
          explanation: '✓ データガバナンスの一環として、テーブルの定義・オーナー・更新頻度・品質ルールを文書化することが重要です。これがなければチームは「このテーブル何を意味するの？」という混乱に陥ります。',
        },
        {
          id: 'q4',
          type: 'fill_blank',
          question: 'Warehouse Layer の注文ファクトテーブルのフルネームを書いてください。（プレフィックス + orders）',
          answer: 'fact_orders',
          placeholder: '????_orders',
          explanation: 'fact_orders が正解です。スタースキーマのファクトテーブルは fact_ プレフィックス、ディメンションテーブルは dim_ プレフィックスを使います（例: dim_users, dim_products）。',
        },
      ],
    },
    {
      id: 'pipeline-design',
      title: 'パイプライン設計クイズ',
      description: '学んだ知識を総まとめ——実践的な判断力を鍛える',
      icon: '🏆',
      xpReward: 60,
      concept: {
        title: 'パイプライン設計は意思決定の連続',
        body: 'どのデータをどのレイヤーで処理するか、依存関係はどうなるか——設計は判断の積み重ねです。\n\n失敗したときに再実行できる冪等性、処理の順序と依存関係、障害時の検知と復旧。これらを考慮して設計することが、実務で使えるデータエンジニアの証です。',
      },
      questions: [
        {
          id: 'q1',
          type: 'multiple_choice',
          question: 'ECサイトの注文データに「amount」カラムがあるが、型がVARCHARで格納されている。これを修正するのは何レイヤーの仕事ですか？',
          options: [
            { label: 'Source Layer', correct: false },
            { label: 'Staging Layer', correct: true },
            { label: 'Warehouse Layer', correct: false },
            { label: 'Mart Layer', correct: false },
          ],
          explanation: '型変換はStaging Layerの仕事です。Source Layerは生データをそのまま保持し、Staging Layerで全ての品質問題を解決します。',
        },
        {
          id: 'q2',
          type: 'true_false',
          question: 'Mart Layer は特定のビジネス目的（例：曜日別売上分析）に特化したテーブルを持つ。',
          correct: true,
          explanation: '✓ Mart Layer はビジネス用途ごとに特化したテーブルを作ります。汎用的なWarehouse Layerとは違い、マーケティング・経営・財務など用途別に最適化します。',
        },
        {
          id: 'q3',
          type: 'multiple_choice',
          question: '新しいデータソースが追加されたとき、最初に行うべき作業はどれですか？',
          options: [
            { label: 'Mart Layer に集計テーブルを作る', correct: false },
            { label: 'Source Layer に生データをそのまま格納する', correct: true },
            { label: 'Staging Layer でクレンジングを始める', correct: false },
            { label: 'スタースキーマを設計する', correct: false },
          ],
          explanation: '常に上流から始めます。まずSource Layerに原本を保存→Stagingでクレンジング→Warehouseでモデリング→Martで集計。この順序を守ることがパイプラインの健全性を保ちます。',
        },
        {
          id: 'q4',
          type: 'ordering',
          question: 'ECサイトの売上分析基盤を構築する作業を、正しい実装順に並べてください。',
          items: [
            '曜日別売上テーブル（mart_sales_by_dow）を作成',
            'orders.csv を src_orders に格納（_loaded_at付き）',
            'スタースキーマ（fact_orders + dim_users）を設計',
            'amount を NUMERIC に型変換して stg_orders を作成',
          ],
          correctOrder: [1, 3, 2, 0],
          explanation: 'Source格納 → Stagingクレンジング → Warehouseモデリング → Mart集計の順です。このフローを守ることでデータの品質と再現性が保証されます。',
        },
        {
          id: 'q5',
          type: 'multiple_choice',
          question: '「売上が最も低い曜日はいつか」という経営判断に使うテーブルはどのレイヤーに置くべきですか？',
          options: [
            { label: 'Source Layer（src_orders）', correct: false },
            { label: 'Staging Layer（stg_orders）', correct: false },
            { label: 'Warehouse Layer（fact_orders）', correct: false },
            { label: 'Mart Layer（mart_sales_by_dow）', correct: true },
          ],
          explanation: 'Mart Layer は「ビジネスの質問に直接答えるテーブル」を持ちます。曜日別集計・KPI・コホートなど特定の意思決定を支えるテーブルはMart Layerです。',
        },
      ],
    },
  ],
};
